version: '3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always
  postgres:
    image: "postgres:latest"
    restart: always
    volumes:
      - /Postgres_data/var/lib/postgresql:/var/lib/postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mobsf
  mobsf:
    build:
      context: .
      dockerfile: Dockerfile
      args:
       - POSTGRES=True
    volumes:
      - /MobSF_data:/root/.MobSF
      - ./uploads:/root/Mobile-Security-Framework-MobSF/uploads
    # devices:
    #   - '/dev/bus/usb:/dev/bus/usb'
    # privileged: true
    depends_on:
      - postgres
      - redis
    links:
      - postgres:postgres
      - redis:redis
    ports:
     - "8000:8000"
